name: tfsec

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      TARGET_PATH:
        required: true
        type: string

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    defaults:
      run:
        working-directory: ${{ inputs.TARGET_PATH }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
